services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    environment:
      - PRAGMA_API_KEY=${PRAGMA_API_KEY}
      - PRAGMA_API_BASE_URL=${PRAGMA_API_BASE_URL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    volumes:
      - .:/opt/pragma-api
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter
